### ISSUE TITLE
Samsung made lifecycle changes

### ISSUE THREAD

**Issue by pakoito** [xxv/android-lifecycle#13]
onCreateOptionsMenu() and onResume() have their order swapped on Samsung devices, we've encountered it in Galaxy S4 and Galaxy Ace.

Can't confirm because it happened 6 months ago.

**Comment by xxv** [comment]
Oh dear.

Is this still valid or worth looking into?

**Comment by pakoito** [comment]
Old version of the OS on old devices, but if you have the phones around and feel adventurous.

**Comment by xxv** [comment]
OK. If you don't mind (I don't have the time or phones) I'll just close this then.
